// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lthmyakloaidtoklooxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0aG15YWtsb2FpZHRva2xvb3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTkzOTUsImV4cCI6MjA3MjAzNTM5NX0.j_M4kdebQI7pa5AqIxHsJKDX7t45QjSg8QiV-mNcBaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});